### ISSUE TITLE
Getting error when creating a AI Session

### ISSUE THREAD

**Issue by designkitt** [Supersagee/AiSeasonCreator#2]
Hello, just tried to create a new AI session but I am getting this messages.

![Snímek obrazovky 2024-04-04 150836](https://github.com/Supersagee/AiSeasonCreator/assets/61963819/9f558b9a-99aa-4eac-ba75-f013661d5f81)

**Comment by designkitt** [comment]
If it helps, it works perfectly fine when option "Static Weather" is checked.

**Comment by Supersagee** [comment]
Hey @designkitt !
Yes, this also happened earlier in the season as well. It seems iRacing is periodically changing the weather url for every race in the schedule API. The weather url grabs the weather forecast for a particular race, and when iRacing changes them all, it renders the old weather urls useless. The issue here, is that I bake in the necessary JSON files without the need for the program to make calls to the API, as that would force users to log in with their iRacing credentials. 

I started working on a solution today, and hope to have it all fixed sometime soon. Thanks!

**Comment by Supersagee** [comment]
I've baked in the necessary keyframes for all of series in my latest release. 403 errors should no longer happen as the program won't be making any calls to the API. Thanks!
